name: dpkfrontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  data_table_2: ^2.1.1
  dio: ^4.0.0
  dropdown_search: ^1.0.3
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_riverpod: ^0.14.0+3
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  global_configuration: 2.0.0-nullsafety.1
  google_fonts: ^2.1.0
  nb_utils: ^4.4.8
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/images/
    - assets/icons/

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
